### ISSUE TITLE
Error on starting

### ISSUE THREAD

**Issue by jprrezende** [ldemattos/openComtradeViewer#13]
Hi, I just installed openComtradeViewer following instructions on Readme file. But I got some problem when I try to execute the script.

A got the message:

`Traceback (most recent call last):
  File "/home/joaopaulo/.local/bin/ocv", line 6, in <module>
    from openComtradeViewer.run import main
  File "/home/joaopaulo/.local/lib/python2.7/site-packages/openComtradeViewer/run.py", line 23, in <module>
    import openComtradeViewer
  File "/home/joaopaulo/.local/lib/python2.7/site-packages/openComtradeViewer/openComtradeViewer.py", line 24, in <module>
    import GUI
  File "/home/joaopaulo/.local/lib/python2.7/site-packages/openComtradeViewer/GUI.py", line 29, in <module>
    import src.pyComtrade as pyComtrade
ImportError: No module named src.pyComtrade
`
Could you help me, please?

Thanks in advance.

**Comment by sergeyblagodarnyy** [comment]
Any update on this? I have the same problem.

**Comment by sergeyblagodarnyy** [comment]
Solved. Just remove `src.` from the import rows in the `~/.local/lib/python2.7/site-packages/openComtradeViewer/GUI.py`
